### ISSUE TITLE
wrap fails with keys from Object.prototype

### ISSUE THREAD

**Issue by megabug** [node-cache-manager/node-cache-manager#183]
If `wrap` is called with a `key` that is the same as the name of a built-in `Object` property, it fails in `CallbackFiller.add`.

For example:

```js
import { default as cacheManager } from 'cache-manager';

const cache = cacheManager.caching();

cache.wrap('constructor', async () => 123);
```

This fails with:

```
[...]/node_modules/cache-manager/lib/callback_filler.js:22
        this.queues[key].push(funcObj);
                         ^

TypeError: this.queues[key].push is not a function
    at CallbackFiller.add ([...]/node_modules/cache-manager/lib/callback_filler.js:22:26)
    at Object.self.wrap ([...]/node_modules/cache-manager/lib/caching.js:181:24)
    at [...]/node_modules/cache-manager/lib/caching.js:52:18
    at new Promise (<anonymous>)
    at Object.wrapPromise ([...]/node_modules/cache-manager/lib/caching.js:51:16)
    at Object.self.wrap ([...]/node_modules/cache-manager/lib/caching.js:168:32)
    at file:///[...]/test.js:5:7
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```

This is at:

```js
CallbackFiller.prototype.add = function(key, funcObj) {
    if (this.queues[key]) {
        this.queues[key].push(funcObj); // <-- here
    } else {
        this.queues[key] = [funcObj];
    }
};
```

This is because `this.queues[key]` returns the built-in `Object.constructor` property, rather than an expected array.

I guess a fix would be to use a `Map` instead of an `Object` for `this.queues`?

**Comment by BryanDonovan** [comment]
Sorry for the delayed response.  You're probably right that a `Map` would work better here.  I can't work on this myself, but would accept a pull request.
